### ISSUE TITLE
deploy new gzweb server using  https://github.com/tork-a/hakuto/pull/26

### ISSUE THREAD

**Issue by 534o** [tork-a/hakuto#29]

**Comment by 130s** [comment]
Done http://54.92.58.250:8080/.

> $ cd %HOME_GZWEB%/http/client/assets     (`assets` folder may not exist. If so, create it)
> $ ln -fs `rospack find tetris_gazebo`/models/apollo15_landing_site_1000x1000 .

The above needed to be re-done using the latest `apollo15_landing_site_1000x1000` folder in order to apply https://github.com/534o/hakuto-1/commit/2ea621b560314071c9fa7a3a4efdfeb7f02baa78.

http://54.92.58.250:8080/joystick.html shows `Not found`.

**Comment by 130s** [comment]
> http://54.92.58.250:8080/joystick.html shows Not found.

Turned out http://54.92.58.250/joystick.html

Seems to be working!
