### ISSUE TITLE
Error and improvement idea for the document

### ISSUE THREAD

**Issue by 130s** [tork-a/hakuto#61]
From https://github.com/tork-a/hakuto/issues/31#issuecomment-174277537 from @angadhn

> I have been following the installation instructions on this page: https://github.com/tork-a/hakuto/blob/master/tetris_launch/doc/sysadmin.rst#run-the-web-simulator-server
> I'm stuck on step 5 of section 4.2.2: specifically, when I run the last command:
> `./coarse_meshes.sh 50 http/client/assets/tetris/`
> I get the following error message:
> ```
> Error: gzcoarse executable not found, exiting.
> ```
> Any suggestions on fixing this would be much appreciated.
>
> Also, I suggest making the installation of gzweb a separate subsection as right now it is in the 'install from source' section and I ended up missing the installation altogether. It would be a minor but helpful change, I think.

----

> Also, for step 6 in the same section, there are 2 issues.
> 1. the diff command has an error since there is no file SkyX_Moon.fragment.org in the specified folder. I did test out that the earth does show up in the simulator so that seems okay.
> 2. The link in the same step is also broken.

**Comment by 130s** [comment]
@angadhn all of your suggestions sound valid. I'll update the document.
For now for your purpose, you can skip gzweb installation 4.2.2 step 4 and 5. In fact if you do 4.2.1, then 4.2.2 isn't necessary (I need confirmation for step 6 and 7 though).

**Comment by angadhn** [comment]
@130s, Sounds good. Step 5 is independent of gzweb though, I imagine; it's the bit that renders the lunar surface, right?

**Comment by 130s** [comment]
Right.

Hopefully the document issue raised here should be resolved in #62.
